### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by pusolito** [hth313/memory-view#1]
Hi @hth313, I'm the author of Doodle. I noticed your project and am curious to know if it is still active. I'm gathering feedback on ways to make Doodle more useful, and would love to hear your feedback so far.

**Comment by hth313** [comment]
It is not active. I prototyped a bit with it to learn Kotlin with the idea to make a user interface. One issue I faced (apart from being new to Kotlin) was that I had to read source code to figure out what to do, I wished for more written documentation at the time.
The major problem for me was that I had no good idea how to tie this into a more appropriate webapp. The plan was to attach to an existing debugger that could provide data. I have used Elm a bit for similar things in the past, but how to make a nice webapp UI in either language has been beyond what I could figure out.
I liked the Doodle project, but I may try Purescript or something Rust based too, then see what I can make out of it. I expect it will be a while before I get there.

**Comment by pusolito** [comment]
Thanks for following up! Did you find it challenging to get docs on Kotlin in general? How about the [docs](https://nacular.github.io/doodle/)/[tutorials](https://nacular.github.io/doodle-tutorials) for Doodle? Were they of any help?

Sounds like you have some more exploration ahead; which is always fun. Good luck! And don't hesitate to reach out if you start trying Doodle again.
